/*
 * This file was generated by the Gradle 'init' task.
 */
project.ext.lwjglVersion = "2.7.1"

plugins {
    id("KobolAdventures.java-application-conventions")
    java
}

dependencies {
    implementation("org.apache.commons:commons-text")
    compile("org.lwjgl:lwjgl:${lwjglVersion}")
    compile("org.lwjgl:lwjgl-platform:${lwjglVersion}:natives-windows")
    compile("org.lwjgl:lwjgl-platform:${lwjglVersion}:natives-linux")
    compile("org.lwjgl:lwjgl-platform:${lwjglVersion}:natives-osx")
}

application {
    // Define the main class for the application.
    mainClass.set("KobolAdventures.app.App")
}
