/*
 * This file was generated by the Gradle 'init' task.
 */
ext["lwjglVersion"] = "2.7.1"

plugins {
    id("KobolAdventures.java-application-conventions")
    java
}

dependencies {
    implementation("org.apache.commons:commons-text")
    compile("org.lwjgl:lwjgl:${project.ext["lwjglVersion"]}")
    compile("org.lwjgl:lwjgl-platform:${project.ext["lwjglVersion"]}:natives-windows")
    compile("org.lwjgl:lwjgl-platform:${project.ext["lwjglVersion"]}:natives-linux")
    compile("org.lwjgl:lwjgl-platform:${project.ext["lwjglVersion"]}:natives-osx")
}

application {
    // Define the main class for the application.
    mainClass.set("KobolAdventures.app.App")
}
