# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Github Commit Timestamp Tagger
      # You may pin to the exact commit or the version.
      # uses: mcpierce/github-commit-timestamp-tagger@8bce13f5e92c6098ae7b83cde10e84aa3ab3db4f
      uses: mcpierce/github-commit-timestamp-tagger@0.0.1
      with:
        # The base version.
        base_version: 1.0.0
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Release
      uses: fnkr/github-action-ghr@v1
      #if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: xz
        GHR_PATH: build/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
